CREATE TABLE [dbo].[TB_CAR](
	[LicensePlate] [varchar](7) NOT NULL,
	[Name] [varchar](20) NULL,
	[ModelYear] [int] NULL,
	[FabricationYear] [int] NULL,
	[Color] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[LicensePlate] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO





CREATE TABLE [dbo].[TB_SERVICE](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Description] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_TB_SERVICE] UNIQUE NONCLUSTERED 
(
	[Description] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO





CREATE TABLE [dbo].[TB_CARSERVICE](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[LicensePlate] [varchar](7) NULL,
	[IdService] [int] NULL,
	[Status] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TB_CARSERVICE]  WITH CHECK ADD  CONSTRAINT [FK_TB_CARROSERVICO_TB_CARRO] FOREIGN KEY([LicensePlate])
REFERENCES [dbo].[TB_CAR] ([LicensePlate])
GO

ALTER TABLE [dbo].[TB_CARSERVICE] CHECK CONSTRAINT [FK_TB_CARROSERVICO_TB_CARRO]
GO

ALTER TABLE [dbo].[TB_CARSERVICE]  WITH CHECK ADD  CONSTRAINT [FK_TB_CARROSERVICO_TB_SERVICO] FOREIGN KEY([IdService])
REFERENCES [dbo].[TB_SERVICE] ([Id])
GO

ALTER TABLE [dbo].[TB_CARSERVICE] CHECK CONSTRAINT [FK_TB_CARROSERVICO_TB_SERVICO]
GO


